name: CI checks

on:
  workflow_call:
  push:
    branches-ignore:
      - 'main'
  pull_request:
    branches:
      - "**"

jobs:
  ci:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.26.2'

      - name: Download dependencies
        run: go mod download

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y libsqlite3-dev

      - name: Run Tests
        run: go test -v ./...

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24'
          cache: 'npm'

      - name: Install Node dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps chromium

      - name: Run Playwright tests
        run: npm run test:e2e

      - uses: actions/upload-artifact@v7
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

      - name: Build
        run: go build -o heat-server .

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag martynvandijke/traces:$(git rev-parse --short HEAD) --tag ghcr.io/martynvdijke/traces:$(git rev-parse --short HEAD)

      - name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Docker image
        run: |          
          docker push martynvandijke/traces:$(git rev-parse --short HEAD)
          docker push ghcr.io/martynvdijke/traces:$(git rev-parse --short HEAD)